name: Run Flake8 in Docker Image

description: >
  Runs flake8 on app code inside docker image.

inputs:
  image_tag:
    description: Docker image tag
    required: true
  image:
    description: Docker image name
    required: true
  registry:
    description: Docker registry (default: ghcr.io)
    default: ghcr.io
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: docker-image

    - run: docker load -i image.tar
      shell: bash

    - run: |
        docker run --rm ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.image_tag }} flake8 --format=default . | tee flake8.txt || true
        cat flake8.txt
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: flake8
        path: flake8.txt

    - run: |
        echo '### 🔍 Flake8 Report' >> $GITHUB_STEP_SUMMARY
        cat flake8.txt | tee /dev/stderr >> $GITHUB_STEP_SUMMARY
      shell: bash
