name: "Resolve Python Package Version from pypi"
description: "Resolve first unused version for a Python package in a generic pypi"
inputs:
  pyproject:
    description: "Path to pyproject.toml"
    required: false
    default: "pyproject.toml"
  registry_url:
    description: "GAR PyPI repo URL (e.g. https://us-central1-python.pkg.dev/my-proj/my-repo/)"
    required: true
  username:
    description: "Username for Basic Auth (e.g. _json_key_base64)"
    required: true
  password:
    description: "Password for Basic Auth (e.g. base64-encoded JSON key)"
    required: true

outputs:
  package:
    description: "Package name"
    value: ${{ steps.resolve.outputs.package }}
  version:
    description: "Resolved new version"
    value: ${{ steps.resolve.outputs.version }}
  package_id:
    description: "Full ID (name==version)"
    value: ${{ steps.resolve.outputs.package_id }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 1.8.4

    - name: Install tools for versioning and parsing
      shell: bash
      run: |
        pip install poetry-dynamic-versioning[plugin]
        pip install toml-cli

    - shell: bash
      id: resolve
      env:
        REPO_URL: ${{ inputs.registry_url }}
        AUTH_HEADER: $(echo -n "${{ inputs.username }}:${{ inputs.password }}" | base64)
      run: |
        BASE_VERSION=$(make version)
        PKG_NAME=$(toml get --toml-path "${{ inputs.pyproject }}" tool.poetry.name | sed 's/"//g')

        echo "📦 Base version: $BASE_VERSION"
        echo "📦 Package name: $PKG_NAME"
        VERSION="$BASE_VERSION"

        # AUTH=$(echo -n "${{ inputs.username }}:${{ inputs.password }}" | base64)
        # URL="${REPO_URL%/}/simple/${PKG_NAME}/"
        # echo "🔍 Fetching version list from: $URL"

        # Fetch and parse all existing versions
        #  EXISTING_VERSIONS=$(curl -sSfL -H "Authorization: Basic $AUTH" "$URL" \
        #  | grep -Eo "${PKG_NAME}-[0-9a-zA-Z_.+-]+\\.(tar\\.gz|whl|zip)" \
        #  | sed -E "s/^${PKG_NAME}-([0-9a-zA-Z_.+-]+)\\.(tar\\.gz|whl|zip)$/\1/" \
        #  | sort -u)

        # echo "📦 Found versions:"
        # echo "$EXISTING_VERSIONS"

        # Resolve final unique version
        # ATTEMPT=0
        # while echo "$EXISTING_VERSIONS" | grep -Fxq "$VERSION"; do
        #  ATTEMPT=$((ATTEMPT + 1))
        #  VERSION="${BASE_VERSION}.${ATTEMPT}"
        # done

        echo "✅ Final resolved version: $VERSION"
        echo "package=$PKG_NAME" >> "$GITHUB_OUTPUT"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "package_id=$PKG_NAME==$VERSION" >> "$GITHUB_OUTPUT"
