name: Publish to PyPI-compatible registry
description: Reusable workflow to build and publish Python packages.

inputs:
  username:
    description: "Username for the PyPI repository"
    required: true
  password:
    description: "Password for the PyPI repository (e.g. base64-encoded key for GAR)"
    required: true
  registry_url:
    description: "URL of the PyPI repository (e.g. https://<region>-python.pkg.dev/...)"
    required: true
  version:
    description: "Force version of the package to publish (e.g. 0.1.0)"
    required: false
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      if: inputs.python-version != ''
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry and Twine
      shell: bash
      run: |
        pip install poetry twine

    - name: Configure Poetry Auth
      shell: bash
      env:
        PYPI_USERNAME: ${{ inputs.username }}
        PYPI_PASSWORD: ${{ inputs.password }}
      run: |
        poetry config http-basic.internal-pypi "$PYPI_USERNAME" "$PYPI_PASSWORD"

    - name: Install dependencies
      shell: bash
      run: |
        poetry install --no-root

    - name: Get Version
      id: get_version
      uses: agent-ix/python-service-actions/latest-pypi-version@main
      with:
        username: ${ inputs.username }
        password: ${{ inputs.password }}
        registry_url: ${{ inputs.registry_url }}

    - name: Build package
      shell: bash
      run: |
        poetry version "${{ steps.get_version.outputs.version }}"
        poetry build

    - name: Upload dist as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
        if-no-files-found: error

    - name: Publish to PyPI-compatible registry
      id: upload
      shell: bash
      run: |
        set +e
        twine upload \
          --verbose \
          --username "${{ inputs.username }}" \
          --password "${{ inputs.password }}" \
          --repository-url "${{ inputs.registry_url }}" \
          dist/* 2>&1 | tee twine_output.txt
        EXIT_CODE=$?
        set -e
        
        if [ $EXIT_CODE -ne 0 ]; then
          if grep -iq "already exists" twine_output.txt || grep -Eiq "409.*conflict" twine_output.txt; then
            echo "skipped=true" >> "$GITHUB_OUTPUT"
            echo "Notice: Package version already exists in registry. Skipping upload."
          else
            echo "Error: Upload failed with error code $EXIT_CODE"
            exit $EXIT_CODE
          fi
        else
          echo "skipped=false" >> "$GITHUB_OUTPUT"
        fi

    - name:  Publish summary
      uses: agent-ix/python-service-actions/pypi-summary@main
      with:
        version: ${{ steps.get_version.outputs.version }}
        package: ${{ github.event.repository.name }}
        registry_url: ${{ inputs.registry_url }}
        skipped: ${{ steps.upload.outputs.skipped }}
