
name: Publish to PyPI-compatible server
description: Publish a Python package using twine

inputs:
  repository_url:
    required: true
  username:
    required: true
  password:
    required: true
  distribution_folder:
    required: false
    default: dist

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade twine
        twine upload --verbose -u "${{ inputs.username }}" -p "${{ inputs.password }}" --repository-url "${{ inputs.repository_url }}" "${{ inputs.distribution_folder }}/*"
