name: Full CI

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image name (e.g. my-org/myapp)"
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
    secrets:
      REGISTRY_USER:
        description: "Docker registry username"
        required: true
      REGISTRY_PASSWORD:
        required: true
        description: "Docker registry password"

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate version tag
        id: get-tag
        shell: bash
        run: |
          version=$(make version)
          echo "image_tag=$version" >> "$GITHUB_OUTPUT"
          echo "Version tag from make version: $version"
      - uses: agent-ix/python-service-actions/build-image@main
        with:
          image: ${{ inputs.image }}
          image_tag: ${{ steps.get-tag.outputs.image_tag }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  pytest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/pytest@main
        with:
          image_tag: ${{ needs.build.outputs.image_tag }}
          image: ${{ inputs.image }}

  black:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/black@main
        with:
          image_tag: ${{ needs.build.outputs.image_tag }}
          image: ${{ inputs.image }}

  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/flake8@main
        with:
          image_tag: ${{ needs.build.outputs.image_tag }}
          image: ${{ inputs.image }}
