name: Full CI

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image name (e.g. my-org/myapp)"
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
    secrets:
      REGISTRY_USER:
        description: "Docker registry username"
        required: true
      REGISTRY_PASSWORD:
        required: true
        description: "Docker registry password"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: agent-ix/python-service-actions/image-metadata@main
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          GITHUB_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: agent-ix/docker-actions/build@main
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}

  pytest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/pytest@main
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  black:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/black@main
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  flake8:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: agent-ix/python-service-actions/flake8@main
        with:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
