name: Reusable Flake8 Runner

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      image:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-image

      - run: docker load -i image.tar

      - name: Run flake8
        id: run_flake8
        continue-on-error: true
        run: |
          set -o pipefail
          docker run --rm ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.image_tag }} \
            flake8 --format=default . | tee flake8.txt

      - name: Upload flake8 output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8
          path: flake8.txt

      - name: Add summary
        if: always()
        run: |
          echo '### 🧼 Flake8 Report' >> $GITHUB_STEP_SUMMARY
          cat flake8.txt | tee /dev/stderr >> $GITHUB_STEP_SUMMARY

      - name: Fail if flake8 failed
        if: steps.run_flake8.outcome != 'success'
        run: exit 1
